version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
#      target: nginx-stage
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
